### PR TITLE
Add OpenSSL libs to CDTs

### PR DESCRIPTION
**Pull request by andfoy**
Please see the repo readme for directions on how to make PRs on this repo.

Checklist:

- [x] if you have added a CDT, it appears in the `cdt_slugs.yaml` file and
  you have rerun the script `python gen_cdt_recipes.py`.
- [ ] if you have changed the CDT generator code (`rpm.py`), you have bumped
  the build number in `conda_build_config.yaml` and have remade all of the
  recipes via running `python gen_cdt_recipes.py --force`
- [ ] if you have added a custom CDT recipe, you have added the name of the CDT
  with `custom: true` in the `cdt_slugs.yaml` file.
- [ ] all CDT recipes have build number set by `{{ cdt_build_number }}` for
  old-style/legacy CDTs or `{{ cdt_build_number|int + 1000 }}` for new-style CDTs
- [ ] if you see a warning about a CDT not having a license, you have added the
  `license_file` key in the `cdt_slugs.yaml` file with the path to the appropriate
  license in `licenses/`

**NOTE: If you make any changes to `cd_slugs.yaml`, you need to reun the generator code
via `python gen_cdt_recipes.py`.**

### CODE REVIEW

**Comment by isuruf** [comment]
We don't want to use CDTs for openssl. Please use the conda package.

**Comment by andfoy** [comment]
This is necessary since CUPS cdt links against OpenSSL 1.0.2 (`libssl.so.10` / `libcrypto.so.10`), whereas conda-forge version produces binaries called `libssl.so.1.0.0` and `libcrypto.1.0.0`. I don't know if there's a better way to fix this conflict

image

image

**Comment by andfoy** [comment]
@isuruf, please see the above comment

**Comment by isuruf** [comment]
Don't use the libcups CDT either. See https://github.com/conda-forge/libcups-feedstock

**Comment by andfoy** [comment]
Got it! Thanks @isuruf

**Pull request closed without merging**
