### PR TITLE
ENH add libglvnd-devel

### PR DESCRIPTION
**Pull request by beckermr**
Please see the repo readme for directions on how to make PRs on this repo.

Checklist:

- [x] if you have added a CDT, it appears in the `cdt_slugs.yaml` file and 
  you have rerun the script `python gen_cdt_recipes.py`.
- [ ] if you have changed the CDT generator code (`rpm.py`), you have bumped
  the build number in `conda_build_config.yaml` and have remade all of the
  recipes via running `python gen_cdt_recipes.py --force`
- [ ] if you have added a custom CDT recipe, you have added the name of the CDT
  with `custom: true` in the `cdt_slugs.yaml` file.
- [ ] all CDT recipes have build number set by `{{ cdt_build_number }}` for
  old-style/legacy CDTs or `{{ cdt_build_number|int + 1000 }}` for new-style CDTs
- [x] if you see a warning about a CDT not having a license, you have added the
  `license_file` key in the `cdt_slugs.yaml` file with the path to the appropriate
  license in `licenses/`

**NOTE: If you make any changes to `cd_slugs.yaml`, you need to reun the generator code
via `python gen_cdt_recipes.py`. Add the `--fast` option to make this go more quickly.**

This PR replaces #45 and incorporates a fix so that old CDT recipes with url-only changes are not edited.

### CODE REVIEW

**Comment by beckermr** [comment]
@basnijholt can you please take a look here and see if the recipes look like they are what you need?

**Comment by basnijholt** [comment]
Yes, this is everything!

**Comment by beckermr** [comment]
Great! I am going to fix the license file stuff here. Can you comment on the extra build script bits. That doesn't appear to do anything...

**Comment by basnijholt** [comment]
It might be correct, I just copied those lines from another package. I wasn’t even sure myself what I was doing. 😅

**Comment by beckermr** [comment]
I see. We should try and find someone who knows this stuff to comment. 

@conda-forge/core?

**Comment by beckermr** [comment]
I see a dep on `mesa-libegl` that looks odd given the other excluded dep.

**Comment by beckermr** [comment]
I didn't see any paths that looked like they need a symlink between mesa-libelg and libglvnd-gles, so I am going to go ahead and merge this. If we need to mark builds as broken later and try again, we can do that.

**Comment by basnijholt** [comment]
Amazing! Thanks a lot for the help 👍

**Pull request merged**
