### PR TITLE
Add at-spi-devel CDT

### PR DESCRIPTION
**Pull request by xhochy**
Please see the repo readme for directions on how to make PRs on this repo.

Checklist:

- [x] if you have added a CDT, it appears in the `cdt_slugs.yaml` file
- [ ] if you have changed the CDT generator code (`rpm.py`), you have bumped
  the build number in `conda_build_config.yaml` and have remade all of the
  recipes via running `python gen_cdt_recipes.py`
- [ ] if you have added a custom CDT recipe, you have added the name of the CDT
  with `custom: true` in the `cdt_slugs.yaml` file.
- [ ] all CDT recipes have build number set by `{{ cdt_build_number }}` for
  old-style/legacy CDTs or `{{ cdt_build_number|int + 1000 }}` for new-style CDTs
- [x] if you see a warning about a CDT not having a license, you have added the
  `license_file` key in the `cdt_slugs.yaml` file with the path to the appropriate
  license in `licenses/`

### CODE REVIEW

**Comment by xhochy** [comment]
Needed for https://github.com/conda-forge/qt-feedstock/pull/158

**Comment by xhochy** [comment]
The script `python gen_cdt_recipes.py` isn't terminating for me anymore :(

**Comment by beckermr** [comment]
> The script python gen_cdt_recipes.py isn't terminating for me anymore :(

Yeah, this happens due to a bug in rpm.py. I add `--recursive` to the call and this causes an error whenever it hits certain packages. You need to set `recursive: false` on one of the recipes and make sure the deps are there by hand.

**Comment by beckermr** [comment]
It will take a bit of guess and check to figure out which one. 

BTW, `rpm.py` is copied from conda-build w/ some changes so we should report this bug upstream.

**Comment by beckermr** [comment]
Also, we need to archive any feedstocks that already build these CDTs and leave an issue on them pointing to this PR.

**Comment by beckermr** [comment]
@xhochy I am pretty sure it is glib2

**Comment by beckermr** [comment]
ack that might be wrong.

**Comment by beckermr** [comment]
fixed - I added a --fast option that uses a global cache for downloads - this is less safe but is a lot faster

**Comment by beckermr** [comment]
There appears to be a race condition with more than one conda build process here. :/

**Comment by beckermr** [comment]
```
total 280
drwxr-xr-x  5 beckermr  staff   160B Jul 20 08:01 .
drwxr-xr-x  5 beckermr  staff   160B Jul 20 08:01 ..
-rwxr-xr-x  1 beckermr  staff    67K Sep 13  2019 pango-list
lrwxr-xr-x  1 beckermr  staff    13B Jul 20 07:39 pango-querymodules-64 -> /usr/bin/true
-rwxr-xr-x  1 beckermr  staff    69K Sep 13  2019 pango-view
```

wtf?

**Pull request merged**
