### PR TITLE
ENH add systemd

### PR DESCRIPTION
**Pull request by mbargull**
Please see the repo readme for directions on how to make PRs on this repo.

Checklist:

- [x] if you have added a CDT, it appears in the `cdt_slugs.yaml` file and 
  you have rerun the script `python gen_cdt_recipes.py`.
- [ ] if you have changed the CDT generator code (`rpm.py`), you have bumped
  the build number in `conda_build_config.yaml` and have remade all of the
  recipes via running `python gen_cdt_recipes.py --force`
- [ ] if you have added a custom CDT recipe, you have added the name of the CDT
  with `custom: true` in the `cdt_slugs.yaml` file.
- [ ] all CDT recipes have build number set by `{{ cdt_build_number }}` for
  old-style/legacy CDTs or `{{ cdt_build_number|int + 1000 }}` for new-style CDTs
- [x] if you see a warning about a CDT not having a license, you have added the
  `license_file` key in the `cdt_slugs.yaml` file with the path to the appropriate
  license in `licenses/`

**NOTE: If you make any changes to `cd_slugs.yaml`, you need to reun the generator code
via `python gen_cdt_recipes.py`. Add the `--fast` option to make this go more quickly.**

### CODE REVIEW

**Comment by mbargull** [comment]
Apart from the ones added to `cdts_slugs.yaml`, this also added `kmod` -- shall I add it to the YAML file, too?

**Comment by beckermr** [comment]
> Apart from the ones added to cdts_slugs.yaml, this also added kmod -- shall I add it to the YAML file, too?

It is not formally required but it can be useful if you don't want to build this CDT on all platforms and centos versions.

**Review by beckermr — APPROVED** [review]

**Comment by mbargull** [comment]
So `kmod` is only available on CentOS 7, so we won't have to skip for 6 :) (and having it for ARM/PPC is fine, of course).
If you think it's good to add it to the list explicitly, then I'll happily added it; if not, also fine by me -- you're the expert here ^^.

Is there anything else I could've/should've done here? I never added a CDT recipe, hence asking.
Essentially, I just added the skip/license fields/files and ran the Python script, but nothing else :O.

**Comment by beckermr** [comment]
The PR looks good and I cannot remember anything else that needs to be done. The code can be a bit finicky when making new CDTs. Sometimes you have to run it more than once. I'd say we merge and hopefully, the things you need get built. If you find they are missing, we can revisit.

**Comment by mbargull** [comment]
Alright, thanks for having taken a look at this (and that you've automated it to be used so conveniently)!

**Comment by beckermr** [comment]
Looks like the api key might be old. I will update it and rekick the builds.

**Pull request merged**
