### PR TITLE
Add cdt for libXft-devel

### PR DESCRIPTION
**Pull request by smithsp**
Checklist:

- [x] if you have added a CDT, it appears in the `cdt_slugs.yaml` file and
  you have rerun the script `python gen_cdt_recipes.py`.
- [x] if you see a warning about a CDT not having a license, you have added the
  `license_file` key in the `cdt_slugs.yaml` file with the path to the appropriate
  license in `licenses/`

### CODE REVIEW

**Comment by beckermr** [comment]
We may need to step back to an older conda/conda-build to get this code to work.

**Comment by smithsp** [comment]
@beckermr Is that action on me somehow?

**Comment by beckermr** [comment]
Likely not unless you want to try. The conda and conda build apis have changed.

**Comment by isuruf** [comment]
Waiting for https://github.com/conda-forge/rpm-tools-feedstock/pull/28

**Comment by isuruf** [comment]
Now the error is about a license file. Did you regenerate the recipes after adding the license_file entry?

**Pull request merged**
