### PR TITLE
Add more CDTs required by Qt

### PR DESCRIPTION
**Pull request by andfoy**
Please see the repo readme for directions on how to make PRs on this repo.

Checklist:

- [x] if you have added a CDT, it appears in the `cdt_slugs.yaml` file and
  you have rerun the script `python gen_cdt_recipes.py`.
- [ ] if you have changed the CDT generator code (`rpm.py`), you have bumped
  the build number in `conda_build_config.yaml` and have remade all of the
  recipes via running `python gen_cdt_recipes.py --force`
- [ ] if you have added a custom CDT recipe, you have added the name of the CDT
  with `custom: true` in the `cdt_slugs.yaml` file.
- [ ] all CDT recipes have build number set by `{{ cdt_build_number }}` for
  old-style/legacy CDTs or `{{ cdt_build_number|int + 1000 }}` for new-style CDTs
- [ ] if you see a warning about a CDT not having a license, you have added the
  `license_file` key in the `cdt_slugs.yaml` file with the path to the appropriate
  license in `licenses/`

**NOTE: If you make any changes to `cd_slugs.yaml`, you need to reun the generator code
via `python gen_cdt_recipes.py`.**

### CODE REVIEW

**Comment by isuruf** [comment]
Why not use https://github.com/conda-forge/avahi-feedstock ?

**Comment by andfoy** [comment]
@beckermr, I think I ran into the same problem as last time

**Comment by andfoy** [comment]
@isuruf, I think that one is for Python? https://anaconda.org/conda-forge/python-avahi

**Comment by andfoy** [comment]
Actually, I downloaded some of the tarballs, and they not contain any binaries

**Comment by beckermr** [comment]
@andfoy Try rerunning the gen script again.

**Comment by isuruf** [comment]
Ah, okay. Let's make a new package for avahi then. CDTs are for low level libraries and avahi doesn't seem to be one.

**Comment by andfoy** [comment]
@isuruf, so should I remove the avahi packages from this PR?

**Comment by beckermr** [comment]
@andfoy I am not sure how you are doing things locally. I simply ran the gen script and it fixed up all of the license issues in your build.

**Comment by isuruf** [comment]
libcom_err is provided by https://github.com/conda-forge/e2fsprogs-feedstock

**Comment by andfoy** [comment]
@beckermr, I'm basically running `python gen_cdt_recipes.py`, I don't know if the fact of being in Ubuntu makes any difference? I had to install `rpm`

**Comment by andfoy** [comment]
So, as a summary, this PR will be closed because we need to create an `avahi` package in staged-recipes and `libcom_err` is being provided by `e2fsprogs`

**Comment by beckermr** [comment]
I am not sure what "basically" means above. Did you kill the script early or anything like that?

**Comment by andfoy** [comment]
> I am not sure what "basically" means above. Did you kill the script early or anything like that?

No, I did not interrupt the script

**Pull request closed without merging**
