### PR TITLE
Add gluh to mesa libgl devel

### PR DESCRIPTION
**Pull request by capn-freako**
Please see the repo readme for directions on how to make PRs on this repo.

Checklist:

- [x] if you have added a CDT, it appears in the `cdt_slugs.yaml` file and
  you have rerun the script `python gen_cdt_recipes.py`.
- [x] if you have changed the CDT generator code (`rpm.py`), you have bumped
  the build number in `conda_build_config.yaml` and have remade all of the
  recipes via running `python gen_cdt_recipes.py --force`
- [x] if you have added a custom CDT recipe, you have added the name of the CDT
  with `custom: true` in the `cdt_slugs.yaml` file.
- [x] all CDT recipes have build number set by `{{ cdt_build_number }}` for
  old-style/legacy CDTs or `{{ cdt_build_number|int + 1000 }}` for new-style CDTs
- [x] if you see a warning about a CDT not having a license, you have added the
  `license_file` key in the `cdt_slugs.yaml` file with the path to the appropriate
  license in `licenses/`

**NOTE: If you make any changes to `cd_slugs.yaml`, you need to reun the generator code
via `python gen_cdt_recipes.py`.**

### CODE REVIEW

**Review by beckermr — COMMENTED** [review]
Is there a reason these are not being made for cos7? We are dropping cos6 at some point.

**Comment by capn-freako** [comment]
No. Actually, I’ve been meaning to ask about that.
I’m just trying to work through my build failures, for the cos6 case, first.
(This is my first attempted contribution and I’m still very confused about how all the pieces fit together.)
-db

**Comment by capn-freako** [comment]
Hi @beckermr , I'm getting this build failure:

> WARNING:conda_build.source:Error: HTTP 404 NOT FOUND for url <[http://mirror.centos.org/centos/7/os/x86_64/Packages/mesa-libGLU-18.3.4-10.el7.x86_64.rpm>](http://mirror.centos.org/centos/7/os/x86_64/Packages/mesa-libGLU-18.3.4-10.el7.x86_64.rpm%3E)

But, I'm able to fetch this file by hand without issue:

```
% curl --output mesa-libGLU-18.3.4-10.el7.x86_64.rpm http://mirror.centos.org/centos/7/os/x86_64/Packages/mesa-libGLU-18.3.4-10.el7.x86_64.rpm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8271  100  8271    0     0  74249      0 --:--:-- --:--:-- --:--:-- 78028
```

Any thoughts?

Thanks,
-db

**Comment by beckermr** [comment]
Ouch I have no idea. Maybe we need to allow redirects or something?

**Comment by capn-freako** [comment]
> Ouch I have no idea. Maybe we need to allow redirects or something?

Is there anyone on the core team, who might have a hunch about this?

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin please restart ci

**Comment by Tobias-Fischer** [comment]
So I've had a quick look - this file does not exist anymore:
curl --output mesa-libGLU-18.3.4-10.el7.x86_64.rpm http://mirror.centos.org/centos/7/os/x86_64/Packages/mesa-libGLU-18.3.4-10.el7.x86_64.rpm

Instead, there is only http://mirror.centos.org/centos/7/os/x86_64/Packages/mesa-libGLU-9.0.0-4.el7.x86_64.rpm
The version difference is very odd though. Not sure what's going on .. do you happen to know @beckermr?

**Comment by Tobias-Fischer** [comment]
I now suspect that the curl command only downloaded the 404 error page, based on the file size above. So I think we just need to change the version. @capn-freako if you give me access to your fork, I'll do it.

**Comment by beckermr** [comment]
@Tobias-Fischer I thought that rpm link was autogenerated, so IDK why it is not there.

**Comment by Tobias-Fischer** [comment]
I think the link was manually generated by changing GL (works) to GLU. Could you please confirm @capn-freako

**Comment by capn-freako** [comment]
> I now suspect that the curl command only downloaded the 404 error page, based on the file size above. So I think we just need to change the version. @capn-freako if you give me access to your fork, I'll do it.

Done.

**Comment by capn-freako** [comment]
> I think the link was manually generated by changing GL (works) to GLU. Could you please confirm @capn-freako

Sorry, I don't understand what my action is here. :(

**Comment by Tobias-Fischer** [comment]
Hi @beckermr @capn-freako - this is the first time I've touched CDTs. All tests are passing, it would be great if you could take a look. Basically all I've done from the groundwork that @capn-freako did is change the version of GLU to 9.0.0 as that is what CentOS7 has.

**Pull request merged**
